name: csd_hotspots
channels:
  - conda-forge
  - defaults
  - https://conda.ccdc.cam.ac.uk/
dependencies:
  - python=3.7
  - tensorflow=2.8
  - pandas=1.2.5
  - pillow=8.4.0
#  - matplotlib
  - numpy=1.21
  - rdkit=2020.09.1.0
  - biopython=1.79
  - csd-python-api
