name: csd_hotspots
channels:
  - defaults
  - conda-forge
  - https://conda.ccdc.cam.ac.uk/
dependencies:
  - python=3.7
  - rdkit::rdkit
  - conda-forge::biopython
  - intel::tensorflow=2.8.0
  - csd-python-api

